name: docker-build-push

on:
  push:
    tags-ignore:
      - 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract branch name
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |-
            linux/arm64
            linux/amd64
          tags: |
            t4skforce/syncthing-relay:latest
            t4skforce/syncthing-relay:${{ env.RELEASE_VERSION }}
            ghcr.io/t4skforce/syncthing-relay:latest
            ghcr.io/t4skforce/syncthing-relay:${{ env.RELEASE_VERSION }}
